<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>PurityUIDashborad</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
    <ProjectReference Include="..\PurityUIDashborad.ViewModels\PurityUIDashborad.ViewModels.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Akbura" />
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>

    <ItemGroup Condition="'$(Configuration)' == 'Debug'">
    <PackageReference Include="Akbura.Diagnostics" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" />
  </ItemGroup>
  </Project>
