using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using PurityUIDashborad.Services;
using System.Globalization;

namespace PurityUIDashborad.ViewModels;

public sealed partial class MainViewModel : ViewModelBase
{
    private readonly IGreetingService _greetingService;

    public MainViewModel(IGreetingService greetingService)
    {
        _greetingService = greetingService ?? throw new ArgumentNullException(nameof(greetingService));
    }

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(CountText))]
    [NotifyCanExecuteChangedFor(nameof(ResetCounterCommand))]
    public partial int Count { get; private set; }

    public string CountText => Count.ToString(CultureInfo.InvariantCulture);

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(Greeting))]
    public partial string? UserName { get; set; } = "Akbura";

    public string Greeting => _greetingService.CreateGreeting(UserName);

    [ObservableProperty]
    private string _generatedStatus = "Generated by CommunityToolkit.Mvvm";

    [RelayCommand]
    private void Increment() => Count++;

    [RelayCommand(CanExecute = nameof(CanResetCounter))]
    private void ResetCounter() => Count = 0;

    private bool CanResetCounter() => Count != 0;

    [RelayCommand]
    private void UseExampleName() => UserName = "Developer";
}
